name: Terraform apply

on:
  workflow_dispatch:

env:
  BUCKET_NAME: "task-6-2"
  AWS_REGION: "ap-northeast-1"

permissions:
  id-token: write
  contents: read
  pull-requests: write

defaults:
  run:
    working-directory: src

jobs:
  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::218138280714:role/task-6-2-role
          role-session-name: task-6-2
          aws-region: ${{ env.AWS_REGION }}
          output-credentials: true

      - name: Send workflow URL to Discord
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"content": "Terraform Apply 準備! 請協助 Approve: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve

      - name: Save Terraform Output
        id: ec2_ip
        run: |
          instance_ip=$(terraform output -raw INSTANCE_IP)
          echo "instance_ip=$instance_ip" >> "$GITHUB_OUTPUT"

        outputs:
          ec2_ip: ${{ steps.ec2_ip.outputs.instance_ip }}
          output1: ${{ steps.ec2_ip.outputs.test }}
