name: Terraform Validation Workflow

on:
  push:
    branches:
      - '**'
    # paths:
    #   - 'src/**'

permissions:
  id-token: write
  contents: read

jobs:
  configure_aws:
    name: Configure AWS Credentials
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::218138280714:role/GitHub-task-6-2
          role-session-name: task-6-2
          aws-region: ${{ env.AWS_REGION }}
          output-credentials: true

  terraform_validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan
