name: "Terraform Validate with GitHub Actions"

on:
  push:
    branches:
      - 'main'
#    paths:
#      - 'src/*'

jobs:
  terraform_validate:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        shell: bash
        working-directory: src  # We keep Terraform files in the terraform directory.

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
