name: "Terraform Validate with GitHub Actions"

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'

jobs:
  terraform_validate:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        shell: bash
        working-directory: ./src  # We keep Terraform files in the terraform directory.

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v3

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform format
        id: fmt
        run: |
          terraform fmt -check

      - name: Terraform validate
        id: validate
        run: |
          terraform validate
