name: Push Check Terraform Validate

on:
  push:
    branches:
      - '**'
#    paths:
#      - 'src/**'

jobs:
  OIDC_Auth&terraform_validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::218138280714:role/GitHub-task-6-2
          role-session-name: task-6-2
          aws-region: ${{ env.AWS_REGION }}
          output-credentials: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
